apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-01-02T13:58:55Z"
  generation: 1
  labels:
    app: ngnix
  name: ngnix
  namespace: default
  resourceVersion: "26528"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/ngnix
  uid: 8b2130ee-0e96-11e9-8d25-0abd6fc207b0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ngnix
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ngnix
    spec:
      containers:
      - image: ngnix
        imagePullPolicy: Always
        name: ngnix
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2019-01-02T13:58:55Z"
    lastUpdateTime: "2019-01-02T13:58:55Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2019-01-02T13:58:55Z"
    lastUpdateTime: "2019-01-02T13:58:55Z"
    message: ReplicaSet "ngnix-7b7d7b5d8" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
